music_directory		    "~/Files/Music"
playlist_directory		"~/.config/mpd/playlists"
db_file			        "~/.config/mpd/database"
log_file			    "syslog"
#state_file			    "~/.config/mpd/state"
#sticker_file			"~/.mpd/sticker.sql"
restore_paused          "yes"
auto_update	            "yes"
#auto_update_depth "3"
audio_output {
        type            "pipewire"
        name            "PipeWire output"
        #target         "bluez_output.F4_9D_8A_B4_8D_37.1"
}
#replaygain			    "album"
#filesystem_charset		"UTF-8"
